version: '3'
services:
  docker:
    build: ./docker
    volumes:
      - ./docker:/usr/src/app
    ports:
      - 5001:8080
  website:
    image: nginx:alpine
    volumes:
      - ./website:/usr/share/nginx/html
    ports:
      - 5002:80
    depends_on:
      - docker